name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: npm install
      - name: install frontend
        run: npm run install:frontend
      - name: install backend
        run: npm run install:backend
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build:frontend
      - name: test backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test:backend
      - name: e2e tests
        env: 
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
      - uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: vast-badlands-46751
          heroku_email: sampopitkanen@hotmail.com
          healthcheck: "https://vast-badlands-46751.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true