name: Periodic Healthcheck

on:
  schedule:
    # disabled to save heroku's free hours
    # - cron: '0/15 * * * *'


jobs:
  periodic_healthchecks:
    runs-on: ubuntu-18.04
    steps:
      - name: Check URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://vast-badlands-46751.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s